services:

  database:
    image: postgres:15.17
    container_name: quizzapp-db
    environment:
      POSTGRES_DB: quizzapp
      POSTGRES_USER: quizzapp
      POSTGRES_PASSWORD: quizzapp
    ports:
      - "5432:5432"
